version: '3.8'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://yespa:0000@mongo:27017/celuflashdb

  mongo:
    build: ./mongodb-docker
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=yespa
      - MONGO_INITDB_ROOT_PASSWORD=0000
      - MONGO_INITDB_DATABASE=celuflashdb
    volumes:
      - /Users/yesidpalencia/Documents/Yesid/Projects/VentasInventario/backend/mongodb-docker/data-celuflash:/data/db

volumes:
  mongodb_data:
